# Generated by Django 4.2 on 2023-05-02 16:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Price pub date')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('value', models.FloatField(verbose_name='Price value')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Service pub date')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Service Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['pub_date'], name='service_ser_pub_dat_7d3580_idx'),
        ),
        migrations.AddField(
            model_name='price',
            name='service',
            field=models.ForeignKey(blank=True, default=service.models.default_service, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='service.service'),
        ),
    ]
