# Generated by Django 4.2 on 2023-05-02 17:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_alter_price_description_alter_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_image",
            field=models.ImageField(blank=True, null=True, upload_to="service", verbose_name="Service Image"),
        ),
        migrations.AlterField(
            model_name="price",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name="Price Description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, default=None, null=True, verbose_name="Service Description"
            ),
        ),
    ]
