# Generated by Django 4.2 on 2023-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_service_service_image_alter_price_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4, verbose_name="Price Value"),
        ),
    ]
