# Generated by Django 4.2 on 2023-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_price_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('photographer', models.CharField(max_length=50, verbose_name='Gallery Photographer')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Gallery pub date')),
                ('place', models.CharField(max_length=50, verbose_name='Gallery place')),
                ('gallery_image_big', models.ImageField(blank=True, null=True, upload_to='gallery_big', verbose_name='Gallery Image Big')),
                ('gallery_image_small', models.ImageField(blank=True, null=True, upload_to='gallery_small', verbose_name='Gallery Image Small')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
