# Generated by Django 4.2 on 2023-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_review_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
    ]
