# Generated by Django 4.2 on 2023-05-07 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0009_rename_event_image_event_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="image",
            new_name="event_image",
        ),
    ]
