# Generated by Django 4.2 on 2023-05-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0010_rename_image_event_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=6, verbose_name="Price Value"),
        ),
    ]
