# Generated by Django 4.2.1 on 2023-05-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0012_event_description_en_event_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="place",
            field=models.CharField(default="", max_length=100, verbose_name="Gallery Place"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="place_en",
            field=models.CharField(default="", max_length=100, verbose_name="Gallery Place En"),
        ),
    ]
