# Generated by Django 4.2.1 on 2023-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0013_alter_gallery_place_alter_gallery_place_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="photographer",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Gallery Photographer"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="photographer_en",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Gallery Photographer En"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="place",
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name="Gallery Place"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="place_en",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, verbose_name="Gallery Place En"
            ),
        ),
    ]
