# Generated by Django 4.2.1 on 2023-05-10 22:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0014_alter_gallery_photographer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, default="", null=True, verbose_name="Price Description"),
        ),
        migrations.AlterField(
            model_name="price",
            name="description_en",
            field=ckeditor.fields.RichTextField(blank=True, default="", null=True, verbose_name="Price Description En"),
        ),
    ]
