# Generated by Django 4.2.1 on 2023-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0015_alter_price_description_alter_price_description_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, default=None, max_length=500, null=True, verbose_name="Service Description"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_en",
            field=models.TextField(
                blank=True, default=None, max_length=500, null=True, verbose_name="Service Description En"
            ),
        ),
    ]
