# Generated by Django 4.2.1 on 2023-05-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0016_alter_service_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active?")),
                ("pub_date", models.DateField(auto_now_add=True, verbose_name="Pub date")),
                ("email", models.EmailField(default=None, max_length=50, verbose_name="Email")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
