# Generated by Django 4.2.1 on 2023-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0017_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(default=None, max_length=50, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_image",
            field=models.ImageField(default=None, upload_to="review", verbose_name="Review Image"),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_image",
            field=models.ImageField(default=None, upload_to="service", verbose_name="Service Image"),
            preserve_default=False,
        ),
    ]
