# Generated by Django 4.2.1 on 2023-06-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0018_alter_email_email_alter_review_review_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallBack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active?")),
                ("pub_date", models.DateField(auto_now_add=True, verbose_name="Pub date")),
                ("name", models.CharField(default=None, max_length=50, verbose_name="Name")),
                ("phone", models.CharField(default=None, max_length=13, verbose_name="Phone")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="review_image",
            field=models.ImageField(upload_to="review", verbose_name="Review Image"),
        ),
    ]
