# Generated by Django 4.2.1 on 2023-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0019_callback_alter_review_review_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callback",
            options={"verbose_name": "Phone number", "verbose_name_plural": "Phone numbers"},
        ),
        migrations.AlterField(
            model_name="event",
            name="event_image",
            field=models.ImageField(default=None, upload_to="event", verbose_name="Event Image"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallery",
            name="gallery_image_big",
            field=models.ImageField(upload_to="gallery_big", verbose_name="Gallery Image Big"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="gallery_image_small",
            field=models.ImageField(upload_to="gallery_small", verbose_name="Gallery Image Small"),
        ),
    ]
