# Generated by Django 4.2.1 on 2023-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0020_alter_callback_options_alter_event_event_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_access",
            field=models.BooleanField(default=None, verbose_name="Is access?"),
            preserve_default=False,
        ),
    ]
